"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on   = "<Enter>"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

# https://yazi-rs.github.io/docs/tips/#cd-to-git-root
[[manager.prepend_keymap]]
on   = [ "g", "r" ]
run  = '''shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm'''
desc = "Go to the root of the git repository"

# https://yazi-rs.github.io/docs/tips/#close-input-by-esc
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
