"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart Filter"

# https://yazi-rs.github.io/docs/tips/#cd-to-git-root
[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = 'shell -- ya emit cd $(git rev-parse --show-toplevel)'
desc = "Go to the root of the git repository"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Projects"
desc = "Jump to projects folder"

[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Jump to root"

# replace zoxide binding with fzf since i don't use zoxide
[[mgr.prepend_keymap]]
on   = "z"
run  = "plugin fzf"
desc = "Jump to a directory or reveal a file using fzf"

[[mgr.prepend_keymap]]
on   = [ "g", "l" ]
run  = "plugin follow-link"
desc = "Follow the symlink"

# https://yazi-rs.github.io/docs/tips/#close-input-by-esc
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
